### ISSUE TITLE
这个exporter，是要docker-compose在哪个主机？

### ISSUE THREAD

**Issue by kwingart** [Bpazy/padavan_exporter#12]
看日志，是要部署在padavan固件上，
但是，padavan不支持docker吧？

如果部署在去监控padavan的那个linux上，那我要去哪里修改ssh连接配置？谢谢。

[root@hp400g1 ~/docker-test/padavan_exporter]#docker-compose logs -f
Attaching to padavan_exporter_comfysub_1
comfysub_1  | time="2023-06-20T00:27:12Z" level=info msg="Connecting to 127.0.0.1:22"
comfysub_1  | time="2023-06-20T00:27:12Z" level=fatal msg="create ssh client failed: dial tcp 127.0.0.1:22: connect: connection refused"
comfysub_1  | time="2023-06-20T00:27:12Z" level=info msg="Connecting to 127.0.0.1:22"
comfysub_1  | time="2023-06-20T00:27:12Z" level=fatal msg="create ssh client failed: dial tcp 127.0.0.1:22: connect: connection refused"
comfysub_1  | time="2023-06-20T00:27:13Z" level=info msg="Connecting to 127.0.0.1:22"
comfysub_1  | time="2023-06-20T00:27:13Z" level=fatal msg="create ssh client failed: dial tcp 127.0.0.1:22: connect: connection refused"
comfysub_1  | time="2023-06-20T00:27:13Z" level=info msg="Connecting to 127.0.0.1:22"
comfysub_1  | time="2023-06-20T00:27:13Z" level=fatal msg="create ssh client failed: dial tcp 127.0.0.1:22: connect: connection refused"
comfysub_1  | time="2023-06-20T00:27:15Z" level=info msg="Connecting to 127.0.0.1:22"
comfysub_1  | time="2023-06-20T00:27:15Z" level=fatal msg="create ssh client failed: dial tcp 127.0.0.1:22: connect: connection refused"
comfysub_1  | time="2023-06-20T00:27:16Z" level=info msg="Connecting to 127.0.0.1:22"
comfysub_1  | time="2023-06-20T00:27:16Z" level=fatal msg="create ssh client failed: dial tcp 127.0.0.1:22: connect: connection refused"

**Comment by Bpazy** [comment]
启动时指定即可：
```sh
$ ./padavan_exporter --padavan.ssh.host="192.168.1.1:22" --padavan.ssh.username="root" --padavan.ssh.password="password"
```

**Comment by kwingart** [comment]
那还是得下载二进制文件了。明白
那这个就没法用docker-compose部署，正如日志显示的会退出。没法运行padavan_exporter
如果一定要用docker-compose部署，有办法在yml文件里面指定ssh连接配置吗？
谢谢！

**Comment by kwingart** [comment]
我这样尝试了下
[root@hp400g1 ~/docker-test/padavan_exporter]#docker-compose up
Creating network "padavan_exporter_default" with the default driver
Creating padavan_exporter_comfysub_1 ... done
Attaching to padavan_exporter_comfysub_1
comfysub_1  | time="2023-06-20T07:32:50Z" level=info msg="Connecting to \"192.168.16.1:22\" --padavan.ssh.username=\"admin\" --padavan.ssh.password=\"iamkwing76\""
comfysub_1  | time="2023-06-20T07:32:50Z" level=fatal msg="create ssh client failed: dial tcp: address tcp/22\" --padavan.ssh.username=\"admin\" --padavan.ssh.password=\"iamkwing76\": unknown port"
padavan_exporter_comfysub_1 exited with code 1

yml文件如下：

version: '3'
services:
  comfysub:
    image: bpazy/padavan_exporter:latest
    restart: always
    ports:
      - "9101:9100"
    command: [--padavan.ssh.host="192.168.16.1:22" --padavan.ssh.username="admin" --padavan.ssh.password="mypasswd"]

**Comment by Bpazy** [comment]
@Bpazy 你的日志里密码泄露了，注意删除下

docker-compose.yaml 实例文件:
```yaml
version: '3'
services:
   padavan_exporter:
        image: bpazy/padavan_exporter:latest
        restart: always
        ports:
            - "9101:9100"
        command: ['--padavan.ssh.host=192.168.31.1:22', "--padavan.ssh.password=password"]
```

注意 command 行多个参数要用数组的形式

**Comment by Bpazy** [comment]
我更新了 docker-compose.yml 示例，你也可以查看下：[docker-compose.yml](https://github.com/Bpazy/padavan_exporter/blob/master/docker-compose.yml)

**Comment by kwingart** [comment]
> @Bpazy 你的日志里密码泄露了，注意删除下。
> 
> docker-compose.yaml 示例文件:
> 
> ```yaml
> version: '3'
> services:
>    padavan_exporter:
>         image: bpazy/padavan_exporter:latest
>         restart: always
>         ports:
>             - "9101:9100"
>         command: ['--padavan.ssh.host=192.168.31.1:22', "--padavan.ssh.password=password"]
> ```
> 
> 注意 command 行多个参数要用数组的形式。

密码没泄露。
原来是参数格式问题，现在docker-compose方式部署ok了。

我刚刚在试那个二进制安装的方式，
命令行运行都没问题，
但是https://blog.csdn.net/hanziyuan08/article/details/107749078里面做成服务的方式，目前那样做，也没用。你程序里面集成的ssh_host参数是127.0.0.1:22，并不是想要监控的padavan固件所在ip

[root@hp400g1 ~]#systemctl status padavan_exporter
● padavan_exporter.service - Node exporter
   Loaded: loaded (/usr/lib/systemd/system/padavan_exporter.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2023-06-20 16:06:55 CST; 1s ago
 Main PID: 26994 (padavan_exporte)
    Tasks: 5
   Memory: 1.3M
   CGroup: /system.slice/padavan_exporter.service
           └─26994 /usr/local/bin/padavan_exporter

Jun 20 16:06:55 hp400g1 systemd[1]: Started Node exporter.
Jun 20 16:06:55 hp400g1 padavan_exporter[26994]: time="2023-06-20T16:06:55+08:00" level=info msg=**"Connecting to 127.0.0.1:22"**

[root@hp400g1 ~]#systemctl status padavan_exporter
● padavan_exporter.service - Node exporter
   Loaded: loaded (/usr/lib/systemd/system/padavan_exporter.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2023-06-20 16:07:17 CST; 3min 23s ago
  Process: 27146 ExecStart=/usr/local/bin/padavan_exporter (code=exited, status=1/FAILURE)
 Main PID: 27146 (code=exited, status=1/FAILURE)

Jun 20 16:07:16 hp400g1 systemd[1]: Unit padavan_exporter.service entered failed state.
Jun 20 16:07:16 hp400g1 systemd[1]: padavan_exporter.service failed.
Jun 20 16:07:17 hp400g1 systemd[1]: padavan_exporter.service holdoff time over, scheduling restart.
Jun 20 16:07:17 hp400g1 systemd[1]: Stopped Node exporter.
Jun 20 16:07:17 hp400g1 systemd[1]: start request repeated too quickly for padavan_exporter.service
Jun 20 16:07:17 hp400g1 systemd[1]: Failed to start Node exporter.
Jun 20 16:07:17 hp400g1 systemd[1]: Unit padavan_exporter.service entered failed state.
Jun 20 16:07:17 hp400g1 systemd[1]: padavan_exporter.service failed.

一直连127.0.0.1，最后启动失败。
有没有办法，把参数通过修改/lib/systemd/system/padavan_exporter.service传进去？
我不懂怎么改
感谢回复。

**Comment by Bpazy** [comment]
@kwingart 你这需求，我理解把参数直接放在后面就可以了，比如：
```sh
[Service]
Type=simple
ExecStart=/usr/local/bin/padavan_exporter --padavan.ssh.host=192.168.31.1:22 --padavan.ssh.password=password
Restart=on-failure
```

**Comment by kwingart** [comment]
我试过，服务没法启动。

**Comment by Bpazy** [comment]
@kwingart 参考这个链接 https://stackoverflow.com/questions/28881758/how-can-i-use-spaces-in-systemd-command-line-arguments

systemd 的参数必须要双引号圈起来，所以应该是:
```sh
[Service]
Type=simple
ExecStart=/usr/local/bin/padavan_exporter "--padavan.ssh.host=192.168.31.1:22 --padavan.ssh.password=password"
Restart=on-failure
```

**Comment by kwingart** [comment]
o ,还是格式问题。谢谢哈
